M48
; DRILL file {KiCad 7.0.6+dfsg-1} date Fri 04 Aug 2023 14:19:36 BST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-04T14:19:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X2.4142Y-2.1301
X2.4142Y-2.4451
X2.4142Y-2.9801
X2.4142Y-3.2951
T0
M30
